[package]
name = "Imu-3D-tracking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.33.0"
plotters = "0.3.6"
serde = "1.0.204"
serial = "0.4.0"
